name: Build and Test

on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test-m4-cluster:
    uses: ./.github/workflows/distributed_job.yml
    with:
      config: '{"M4PRO_GPU16_24GB": 2}'
      model: 'llama-3.2-1b'
    secrets: inherit